config/routes.rb
RailsPortfolio::Application.routes.draw do
  
  #----------------Pages Controller----------------------#
  
  get "home" => 'pages#welcome', :as => "welcome"
  
  get "about" => 'pages#bio', :as => "bio"
  
  #---------------ClassProject Model----------------#
  
  get "classprojects" => 'class_projects#index', :as => "class_project"
  
  get "classprojects/new" => 'class_projects#new', :as => "project_new"
  get "classprojects/:id/edit" => 'class_projects#edit', :as => "project_edit"
  
  post "classprojects" => 'class_projects#create' # Notice that the path 'classprojects' is the same as the index path.
  put "classprojects/:id" => 'class_projects#update' # Notice that the path 'classprojects/:id' is the same as the show route.
  
  get "classprojects/:id" => 'class_projects#show', :as => "project"
  delete "classprojects/:id/delete" => 'classprojects#destroy', as: 'project_delete'
  
  #-----------------Contacts Model-------------------#
  
  get "contacts" => 'contacts#index', :as => "contacts"
  
  get "contacts/new" => 'contacts#new', :as => "contact_new"
  get "contacts/:id/edit" => 'contact#edit', :as => "contact_edit"
  
  post "contacts" => 'contacts#create'
  put "contacts/:id" => 'contacts#update'
  
  get "contacts/:id" => 'contacts#show', :as => "contact"
  delete "contacts/:id/delete" => 'contacts#destroy', as: 'contact_delete'
  
  #------------------Article Model--------------------#
  
  get "articles" => 'articles#index', :as => "article_list"
  
  get "articles/new" => 'articles#new', :as => "article_new"
  get "articles/:id/edit" => 'articles#edit', :as => "article_edit"
  
  post "articles" => 'articles#create'
  put "articles/:id" => 'articles#update'
  
  get "articles/:id" => 'articles#show', :as => "article"
  delete 'articles/:id/delete' => 'articles#destroy', as: 'article_delete'
  
  #-------------------Like Model-----------------------#
  
  get "likes" => 'likes#index', as: 'likes'
  
  get 'likes/new' => 'likes#new', as: 'new_like'
  get 'likes/:id/edit' => 'likes#edit', as: 'edit_like'
  
  post 'likes' => 'likes#create'
  put 'likes/:id' => 'likes#update'
  
  get 'likes/:id' => 'likes#show', as: 'like'
  delete 'likes/:id/delete' => 'likes#destroy', as: 'delete_like'
  
  #------------------Login Conrtoller-----------------------#
  
  get "login" => 'logins#new', :as => "login"
  post "login" => 'logins#create', :as => "login_create"
  get "logout" => 'logins#destroy', :as => "logout"
 
  #-------------------User Model-----------------------#
  
  post "create_user" => 'users#create', :as => "user_create"
  get "signup" => 'users#new', :as => "signup"
  

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :body, :draft, :title
  
  scope :draft, -> { where(draft: true) }
  scope :published, -> { where(draft: false) }
  
  def excerpt
    self.body.slice(0,30)
  end
  
  def relative_length
    if self.body.length <= 50
      "Short"
    elsif self.body.length <= 100
      "Medium"
    else self.body.length <= 150
      "Long"
    end
  end
end

app/models/class_project.rb
class ClassProject < ActiveRecord::Base
  attr_accessible :code_language, :github, :name, :summary
  
  validates :name, :summary, :code_language, :github, :presence => true

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :email, :message, :name
  
  validates :email, :message, :name, :presence => true
end

app/models/like.rb
class Like < ActiveRecord::Base
  attr_accessible :article_id, :ip_address


end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  def index
    @articles = Article.all
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(params[:article])
    
    if @article.save
      redirect_to article_list_path
    else
      render "new"
    end
  end
  
  def edit
    @existing_article = Article.find(params[:id])
  end
  
  def update
    @existing_article = Article.find(params[:id])
    
    if @existing_article.update_attributes(params[:article])
      redirect_to article_list_path(@existing_article.id)
    else
      render "edit"
    end
  end
  
  def show
    @article = Article.find(params[:id])
    @like = Like.new
    
    @all_likes = Like.where({article_id: params[:id]})
    
    @ip = true
    
    @all_likes.each do |a|
      if a.ip_address == request.remote_ip
        @ip = false
      end
    end
  end
  
  def destory
    @article = Article.find(params[:id])
    @article.destroy
    
    redirect_to article_list_path
  end
  
      
end

app/controllers/class_projects_controller.rb
class ClassProjectsController < ApplicationController

  def index
    @class_projects = ClassProject.all
  end
  
  def new
    @class_project = ClassProject.new
  end

  def create
    @class_project = ClassProject.new(params[:class_project])
    
    if @class_project.save
      redirect_to class_project_path
    else
      render "new"
    end
  end
  
  def edit
    @existing_project = ClassProject.find(params[:id])
  end
  
  def update
    @existing_project = ClassProject.find(params[:id])
    
    if @existing_project.update_attributes(params[:class_project])
      redirect_to class_project_path(@existing_project.id)
    else
      render "edit"
    end
  end
  
  def show
    @class_project = ClassProject.find(params[:id])
  end
  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  def index
    @contacts = Contact.all
  end
  
  def new
    @contact = Contact.new
  end
  
  def create
    @contact = Contact.new(params[:contact])
    
    if @contact.save
      redirect_to contact_list_path
    else
      render "new"
    end
  end
  
  def edit
    @existing_contact = Contact.find(params[:id])
  end
  
  def update
    @existing_contact = Contact.find(params[:id])
    
    if @existing_contact.update_attributes(params[:contact])
      redirect_to contact_list_path(@existing_contact.id)
    else
      render "edit"
    end
  end
  
  def show
    @contact = Contact.find(params[:id])
  end
  
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def index
    redirect_to article_list_path
  end
  
  def create
    @like = Like.new(params[:like])
    
    if @like.save
      redirect_to article_list_path(session[:id])
    else
      redirect_to root_path
    end 
  end

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController

  def new
  end
 
  def create
    # Check if the email/password is a match to log someone in.
    user = User.find_by_email(params[:email])
    
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to welcome_path
    else
      raise "Invalid login."
    end
 end
 
 def destroy
   session[:user_id] = nil
   redirect_to article_list_path
 end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  # This directs our 'welcome' route
  def welcome
  end
  
  # This directs our 'bio' route
  def bio
  end
  
  # This directs our 'twitter' route
  def twitter
  end
  
  # This directs our 'linkedin' route
  def linkedin
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    
    if @user.save
      redirect_to article_list_path
    else
      raise "User could not be saved."
    end
  
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/class_projects_helper.rb
module ClassProjectsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<% @existing_article.errors.full_messages.each do |msg| %>
	<p><%= msg %></p>
<% end %>

<!-- Creates a PUT request to "/users/1/edit" -->
<%#= form_for(@existing_recruit, :as => "user", :url => user_path(@existing_recruit.id), :method => "put") ... %>

<%= form_for @existing_article, :url => "/articles/#{@existing_article.id}" do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	
	<%= f.label :body %>
	<%= f.text_field :body %>
	
	<%= f.label :draft %>
	<%= f.text_field :draft %>
	
	<%= f.submit %>
	
<% end %>

<p>_________________________________________________________</p>

<ul>
	<li><%= link_to("Home", welcome_path) %></li>
	<li><%= link_to("Class Projects", class_project_path) %></li>
	<li><%= link_to("Contacts", contacts_path) %></li>
</ul>

app/views/articles/index.html.erb
<h1>Articles</h1>

<% @articles.each do |article| %>

<!-- We could run this tag
	<! <p><a href="<%#= article_list_path(contact.id) %>"><%#= article.title %></a></p> -->
<!-- But the link_to approach is the much more conventional 'rails way' -->

<p><%= link_to(article.title, article_path(article.id)) %></p>

<% end %>

<%= link_to("Create new article", article_new_path) %>

<p>_________________________________________________________</p>

<ul>
	<li><%= link_to("Home", welcome_path) %></li>
	<li><%= link_to("Class Projects", class_project_path) %></li>
	<li><%= link_to("Contacts", contacts_path) %></li>
</ul>

app/views/articles/new.html.erb
<h1>New Article</h1>

<% @article.errors.full_messages.each do |msg| %>

<p><%= msg %></p>

<% end %>

	<!-- Creates a POST request to "/articles" -->

<%= form_for @article, :url => "/articles" do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	
	<%= f.label :body %>
	<%= f.text_field :body %>
	
	<%= f.label :draft %>
	<%= f.text_field :draft %>
	
	<%= f.submit %>
	
<% end %>

<p>_________________________________________________________</p>

<ul>
	<li><%= link_to("Home", welcome_path) %></li>
	<li><%= link_to("Class Projects", class_project_path) %></li>
	<li><%= link_to("Contacts", contacts_path) %></li>
</ul>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<%= session[:id] %>

<p><%= @article.body %></p>

<p><%= @article.draft %></p>

<p>Likes: <%= @all_likes.length %></p>

<% if @ip %>
	<%= form_for @like do |f| %>
		<%= f.hidden_field :article_id, value: @article.id %>
		<%= f.hidden_field :ip_address, value: request.remote_ip %>
		<%= f.submit value: "Like" %>
	<% end %>
<% end %>


<%= link_to("Edit this Article", article_edit_path(@article.id)) %>

<p>_________________________________________________________</p>

<ul>
	<li><%= link_to("Home", welcome_path) %></li>
	<li><%= link_to("Class Projects", class_project_path) %></li>
	<li><%= link_to("Contacts", contacts_path) %></li>
</ul>

app/views/class_projects/edit.html.erb
<h1>Edit Project</h1>

<% @existing_project.errors.full_messages.each do |msg| %>
	<p><%= msg %></p>
<% end %>

<!-- Creates a PUT request to "/users/1/edit" -->
<%#= form_for(@existing_recruit, :as => "user", :url => user_path(@existing_recruit.id), :method => "put") ... %>

<%= form_for @existing_project, :url => "/classprojects/#{@existing_project.id}" do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	
	<%= f.label :summary %>
	<%= f.text_field :summary %>
	
	<%= f.label :code_language %>
	<%= f.text_field :code_language %>
	
	<%= f.label :github %>
	<%= f.text_field :github %>
	
	<%= f.submit %>
	
<% end %>

<p>_________________________________________________________</p>

<ul>
	<li><%= link_to("Home", welcome_path) %></li>
	<li><%= link_to("Articles", article_list_path) %></li>
	<li><%= link_to("Contacts", contacts_path) %></li>
</ul>

app/views/class_projects/index.html.erb
<h1>Omaha Code School Projects</h1>

<% @class_projects.each do |classproject| %>

<!-- We could run this tag
	<! <p><a href="<%#= user_path(user.id) %>"><%#= user.name %></a></p> -->
<!-- But the link_to approach is the much more conventional 'rails way' -->

<p><%= link_to(classproject.name, project_path(classproject.id)) %></p>

<% end %>

<%= link_to("Create new Project", project_new_path) %>

<p>_________________________________________________________</p>

<ul>
	<li><%= link_to("Home", welcome_path) %></li>
	<li><%= link_to("Articles", article_list_path) %></li>
	<li><%= link_to("Contact", contacts_path) %></li>
</ul>

app/views/class_projects/new.html.erb
<h1>New Project</h1>

<% @class_project.errors.full_messages.each do |msg| %>

<p><%= msg %></p>

<% end %>

<!-- Creates a POST request to "/classprojects" -->

<%= form_for @class_project, :url => "/classprojects" do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	
	<%= f.label :summary %>
	<%= f.text_field :summary %>
	
	<%= f.label :code_language %>
	<%= f.text_field :code_language %>
	
	<%= f.label :github %>
	<%= f.text_field :github %>
	
	<%= f.submit %>
	
<% end %>

<p>_________________________________________________________</p>

<ul>
	<li><%= link_to("Home", welcome_path) %></li>
	<li><%= link_to("Articles", article_list_path) %></li>
	<li><%= link_to("Contacts", contacts_path) %></li>
</ul>

app/views/class_projects/show.html.erb
<h1><%= @class_project.name %></h1>

<p><%= @class_project.summary %></p>
<p><%= @class_project.code_language %></p>
<p><%= @class_project.github %></p>

<%= link_to("Edit this project", project_edit_path(@class_project.id)) %>

<p>_________________________________________________________</p>

<ul>
	<li><%= link_to("Home", welcome_path) %></li>
	<li><%= link_to("Articles", article_list_path) %></li>
	<li><%= link_to("Contacts", contacts_path) %></li>
</ul>

app/views/contacts/edit.html.erb
<h1>Edit Contact</h1>

<% @existing_contact.errors.full_messages.each do |msg| %>
	<p><%= msg %></p>
<% end %>

<!-- Creates a PUT request to "/users/1/edit" -->
<%#= form_for(@existing_recruit, :as => "user", :url => user_path(@existing_recruit.id), :method => "put") ... %>

<%= form_for @existing_contact, :url => "/contacts/#{@existing_contact.id}" do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	
	<%= f.label :email %>
	<%= f.text_field :email %>
	
	<%= f.label :message %>
	<%= f.text_field :message %>
	
	<%= f.submit %>
	
<% end %>

<p>_________________________________________________________</p>

<ul>
	<li><%= link_to("Home", welcome_path) %></li>
	<li><%= link_to("Class Projects", class_project_path) %></li>
	<li><%= link_to("Articles", article_list_path) %></li>
</ul>

app/views/contacts/index.html.erb
<h1>My Contacts</h1>

<% @contacts.each do |contact| %>

<!-- We could run this tag
	<! <p><a href="<%#= contact_list_path(contact.id) %>"><%#= contact.name %></a></p> -->
<!-- But the link_to approach is the much more conventional 'rails way' -->

<p><%= link_to(contact.name, contact_path(contact.id)) %></p>

<% end %>

<%= link_to("Create new Contact", contact_new_path) %>

<p>_________________________________________________________</p>

<ul>
	<li><%= link_to("Home", welcome_path) %></li>
	<li><%= link_to("Class Projects", class_project_path) %></li>
	<li><%= link_to("Articles", article_list_path) %></li>
</ul>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<% @contact.errors.full_messages.each do |msg| %>

<p><%= msg %></p>

<% end %>

<!-- Creates a POST request to "/contacts" -->

<%= form_for @contact, :url => "/contacts" do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	
	<%= f.label :email %>
	<%= f.text_field :email %>
	
	<%= f.label :message %>
	<%= f.text_field :message %>
	
	<%= f.submit %>
	
<% end %>

<p>_________________________________________________________</p>

<ul>
	<li><%= link_to("Home", welcome_path) %></li>
	<li><%= link_to("Class Projects", class_project_path) %></li>
	<li><%= link_to("Articles", article_list_path) %></li>
</ul>

app/views/contacts/show.html.erb
<h1><%= @contact.name %></h1>

<p><%= @contact.email %></p>
<p><%= @contact.message %></p>

<%= link_to("Edit this Contact", contact_edit_path(@contact.id)) %>

<p>_________________________________________________________</p>

<ul>
	<li><%= link_to("Home", welcome_path) %></li>
	<li><%= link_to("Class Projects", class_project_path) %></li>
	<li><%= link_to("Articles", article_list_path) %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsPortfolio</title>
  <link href='http://fonts.googleapis.com/css?family=Special+Elite' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Homemade+Apple' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>
  
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">

<!-- <p><%= session %></p> -->

	<div id="preheader">
		<% if current_user %>
		<%= current_user.email %> (<%= link_to "Log out!", logout_path %>)
		<% else %>
		<%= link_to("Log In", login_path) %>
		<% end %>
	</div>

	<header class="cf">
		<h1 class="cf"><a href="<%= welcome_path %>">Corey Burkley</a></h1>
	</header>

	<div id="postheader" class="cf"></div>
	
	<nav class="cf">
		<ul>
			<li><%= link_to("Articles", article_list_path) %></li>
			<li><%= link_to("Projects", class_project_path) %></li>
			<li><%= link_to("Contact", contact_new_path) %></li>
		</ul>
	</nav>

	<div id="main" class="cf">
		<% if flash[:notice] %>
		<p id="notice"><%= flash[:notice] %></p>
		<% end %>
		<% if flash[:alert] %>
		<p id="alert"><%= flash[:alert] %></p>
		<% end %>

<%= yield %>
	</div>

</div>


</body>
</html>

app/views/logins/new.html.erb
<h1>Log In</h1>

	<%= form_tag login_create_path do %>
	
	<div class="field">
		<%= label_tag :email %><br />
		<%= text_field_tag :email, params[:email] %>
	</div>

	<div class="field">
		<%= label_tag :password %><br />
		<%= password_field_tag :password %>
	</div>

<%= submit_tag "Log In" %>

<% end %>

	<p>___________________________________________</p>
	
	<ul>
		<li><%= link_to("Home", welcome_path) %></li>
		<li><%= link_to("Class Projects", class_project_path) %></li>
		<li><%= link_to("Contacts", contacts_path) %></li>
		<li><%= link_to("My Articles", article_list_path) %></li>
	</ul>	

app/views/pages/bio.html.erb
<h1>About me</h1>

<p>My name is Corey Burkley.  I am a student at Omaha Code School.</p>

<p><a href="https://twitter.com/HappyHourHusker">Follow me on Twitter</a></p>	
<p><a href="https://www.linkedin.com/in/coreyburkley">Connect with me on Linkedin</a></p>

app/views/pages/welcome.html.erb
<h1>Corey Burkley's Portfolio</h1>
	
	<p>This is my blog</p>
	
	<p>___________________________________________</p>
	
	<ul>
		<li><%= link_to("About me", bio_path) %></li>
		<li><%= link_to("Class Projects", class_project_path) %></li>
		<li><%= link_to("Contacts", contacts_path) %></li>
		<li><%= link_to("My Articles", article_list_path) %></li>
	</ul>
	
	<p>___________________________________________</p>

<%= link_to("Log in", login_path) %> |	
<%= link_to("Sign up!", signup_path) %>
	

app/views/users/new.html.erb
<h1>Sign Up</h1>

	<%= form_for @user, :url => user_create_path do |f| %>
	<p>
		<%= f.label :email %>
		<%= f.text_field :email %>
	</p>

	<p>
		<%= f.label :password %>
		<%= f.password_field :password %>
	</p>

	<p>
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation %>
	</p>

<%= f.submit %>

<% end %>

	<p>___________________________________________</p>
	
	<ul>
		<li><%= link_to("Home", welcome_path) %></li>
		<li><%= link_to("Class Projects", class_project_path) %></li>
		<li><%= link_to("Contacts", contacts_path) %></li>
		<li><%= link_to("My Articles", article_list_path) %></li>
	</ul>	